main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('qna/', views.qna, name='qna'),
    path('oldwebsite/', views.oldweb, name='oldweb'),
    path('addmatkul/', views.addmatkul, name='addmatkul'),
    path('matkuls/', views.showmatkul, name="showmatkul"),
    path('delete_matkul/<str:pk>/', views.deleteMatkul, name="deletematkul")
]

pepewe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls'))
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
	path('', views.index, name='index'),
	path('addKegiatan/', views.addKegiatan, name="addKegiatan"),
	path('addPeserta/<str:pk>/', views.addPeserta, name="addPeserta")
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
	path('', views.index, name='index')
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
	path('', views.index, name='index'),
	path('data/', views.json_data, name='data')
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.login, name='login')
]

main/models.py
from django.db import models


class Matkul(models.Model):
	nama_matkul = models.CharField(max_length = 30)
	dosen_pengajar = models.CharField(max_length = 30)
	jumlah_sks = models.CharField(max_length = 2)
	deskripsi = models.TextField()
	ruang_kelas = models.CharField(max_length = 15)

	def __str__(self):
		return self.nama_matkul

story6/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
	name = models.CharField(max_length = 30)

	def __str__(self):
		return self.name

class Kegiatan(models.Model):
	name = models.CharField(max_length = 30)
	peserta = models.ManyToManyField(Person)

	def __str__(self):
		return self.name

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
	class Meta:
		model = Matkul
		fields = ['nama_matkul', 'dosen_pengajar', 'jumlah_sks', 'deskripsi', 'ruang_kelas']


	

story6/forms.py
from django import forms
from .models import Kegiatan, Person

class KegiatanForm(forms.ModelForm):
	class Meta:
		model = Kegiatan
		fields = ['name']

class PersonForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = ["name"]

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect
from .forms import MatkulForm
from django.http import HttpResponseRedirect
from .models import Matkul

def home(request):
    return render(request, 'main/story3-page1.html')

def qna(request):
	return render(request, 'main/story3-page2.html')

def oldweb(request):
	return render(request, 'main/story1.html')

def addmatkul(request):
	if request.method == 'POST' :
		form = MatkulForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/matkuls')


	form = MatkulForm()
	return render(request, 'main/story5-page1.html', { 'form': form })

def deleteMatkul(request, pk):
	matkul = Matkul.objects.get(id=pk)
	if request.method=='POST':
		matkul.delete()
		return redirect('/matkuls')

	response = {'item' : matkul}
	return render(request, "main/story5-delete.html", response)


def showmatkul(request):
	matkuls = Matkul.objects.all()
	response = {'matkuls' : matkuls}
	html = 'main/story5-page2.html'
	return render(request, html, response)

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import KegiatanForm, PersonForm
from .models import Kegiatan, Person

# Create your views here.
def index(request):
	kegiatans = Kegiatan.objects.all()
	response = {'kegiatans' : kegiatans}
	return render(request, 'story6/kegiatan.html', response)

def addKegiatan(request):
	if request.method =='POST':
		form = KegiatanForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/story6')

	form = KegiatanForm()
	return render(request, 'story6/addKegiatan.html', {'form' : form})

def addPeserta(request, pk):
	kegiatan = Kegiatan.objects.get(id=pk)
	if request.method=='POST':
		form = PersonForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			form.save()
			pesertaBaru = Person.objects.get(name=data["name"])
			kegiatan.peserta.add(pesertaBaru)
			

			return redirect('/story6')

	form = PersonForm()
	response = {'form' : form}
	return render(request, "story6/addPeserta.html", response)

story7/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def index(request):
	return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
	return render(request, 'story8/index.html')

def json_data(request):
	url = 	'https://www.googleapis.com/books/v1/volumes?q='+request.GET['q']
	link = requests.get(url)
	json_text = link.text
	data = json.loads(json_text)
	return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib import messages

# Create your views here.
def index(request):
	return render(request, 'story9/index.html')

def signup(request):
	form = CreateUserForm()

	if request.method == "POST":
		form = CreateUserForm(request.POST)
		if form.is_valid():
			uname = form.cleaned_data['username']
			email = form.cleaned_data['email']
			pass1 = form.cleaned_data['password1']
			new_user = User.objects.create_user(uname, email=email, password=pass1, is_staff=True)
			new_user.save()
			return redirect('/story9/login/')

	response = {'form': form}
	return render(request, 'story9/signup.html', response)

def login(request):
	
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(request, username=username, password=password)
		if user is not None:
			auth_login(request, user)
			return redirect('/story9/')
		else:
			response = {'error_message' : 'username OR password incorrect'}
			return render(request, 'story9/login.html', response)


	response = {}
	return render(request, 'story9/login.html', response)

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}Rio Fernando Alexander{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-style">
            <h2 id=judul>{% block judulAtas %}Rio Fernando{% endblock %}</h2>
            
        </nav>
    </header>
    
   {% block content %}
   {% endblock %}
    

    
</body>
</html>

main/templates/main/story1.html
{% load static %}
{% extends 'main/base.html' %}


{% block content %}
<div class="inaBox">
    <img src="{% static 'img/MY50.jpg' %}" class="img-responsive" width="200" height="210">
</div>
<div class="inaBox">
    <p> Nama: Rio Fernando </p>
    <p> Angkatan: 2019</p>
    <p> Kampus: Universitas Indonesia </p>
    <p>Riwayat Pendidikan:</p>
    <table border="1" width="40%">
        <tr>
            <th>Periode</th>
        <tr>
            <th>2019-Sekarang</th>
            <th>Universitas Indonesia</th>
        </tr>
    </table>
    
</div>
<div class="textcenter">
    <button class="button">
        <a href="{% url 'main:home' %}">My updated website</a>
    </button>
</div>
{% endblock %}

main/templates/main/story3-page1.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-4">
        <img src="{% static 'img/MY50.jpg' %}" class="img-rounded" id="foto">
    </div>
    <div id="desc">
        <h1 id="nama">Rio Fernando Alexander</h1>
        <p id="jabatan">Undergraduate Student in University of Indonesia</p>
    </div>
    <div class="inaBox" id="desc">
        <p>Saya saat ini sedang mengambil mata kuliah perancangan dan pemrograman web.
        Saya sangat sadar bahwa website ini tidak enak dilihat, sehingga saya akan belajar terus menerus untuk meningkatkan 
        kemampuan saya dalam membuat sebuah website. 
        Enggan mendesain terlalu bagus karena takut tidak bisa mengimplementasikan dengan baik.
            </p>
    </div>

    <div class="textcenter">
        <a class="btn btn-second" href="{% url 'main:qna' %}">Ask me a Question?</a>
        <a class="btn btn-third" href="{% url 'main:showmatkul' %}"> Mata Kuliah!</a>
    </div>

    <div class="textcenter">
        <a class="btn btn-first" href="{% url 'story6:index' %}"> Story6 </a>
        <a class="btn btn-second" href="{% url 'story7:index' %}"> Story7 - JavaScript </a>
        <a class="btn btn-third" href="{% url 'story8:index' %}">Story8 - AJaX</a>
    </div>

    <div class="textcenter">
        <a class="btn btn-first" href="{% url 'story9:index' %}"> Story9</a>
    </div>

    <div  class="inaBox">
        <h1>Riwayat Pendidikan</h1>
        <table border="0" width="60%" class="table table-borderless">
            <tr>
                <td><p class="tulGede">Universitas Indonesia</p>
                    <p class="tulKecil">Fakultas Ilmu komputer</p></td>
                <td class="tulGede">2019-Sekarang</td>
            </tr>
            <tr>
                <td><p class="tulGede">SMAN 1 Lubuk Pakam</p>
                    <p class="tulKecil">Matematika dan Ilmu Pengetahuan Alam</p></td>
                <td class="tulGede">2016-2019</td>
            </tr>
            <tr>
                <td class="tulGede">SMPN 1 Tanjung Morawa</td>
                <td class="tulGede">2013-2016</td>
            </tr>
        </table>
        

    </div>

    <div class="inaBox">
        <h1>Pengalaman Organisasi</h1>
        <div>
            <p class="tulGede">COMPFEST 12</p>
            <p class="tulKecil">Staff of Business IT Case</p>
        </div>
        <div>
            <p class="tulGede">UI MUN Club</p>
            <p class="tulKecil">Member</p>
        </div>
        <div>
            <p class="tulGede">StudentsCatalyst</p>
            <p class="tulKecil">Students</p>
        </div>
    </div>

    <div class="inaBox">
        <table border="0" width="60%" class="table table-borderless">
            <tr>
                <th class="tulGede">Projects</th>
                <th class="tulGede">Skills</th>
            </tr>
            <tr>
                <td>
                <td class="tulGede">Python Programming</td>
            </tr>
            <tr>
                <td></td>
                <td class="tulGede">Microsoft Word</td>
            </tr>
            <tr>
                <td></td>
                <td class="tulGede">Debate</td>
            </tr>
        </table>
    </div>


    <footer class="footer">
        <div id="contact">
            <h1>Contact Me</h1>
            <div class="inaBox">
                <p>@rio_fernando_</p>
                <p>linkedin.com/in/rio_fernando_</p>
            </div>
        </div>
    </footer>
    
{% endblock %}

main/templates/main/story3-page2.html
{% extends 'main/base.html' %}
{% block title %}Ask me!{% endblock %}
{% load static %} 
{% block content%}   
    <div class="inaBox">
        <label class="tulKecil" for="fname">Nama:</label>
        <input type="text" class="form-control" name="fname"><br><br>
        <label class="tulKecil" for="fmail">Email:</label>
        <input type="text" class="form-control" name="fmail">
        <label class="tulKecil" for="question">Message:</label>
        <textarea type="text" class="form-control" rows="5" name="message" ></textarea>
    </div>

    <div class="text-center">
        <a class="btn btn-first" href="{% url 'main:home' %}">Back</a>
        <a class="btn btn-second" id="buttondua" href="#">Submit</a>
    </div>
{% endblock %}

main/templates/main/story5-delete.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Mata Kuliah!{% endblock %}
{% load static %} 
{% block content%}

<p> Are you sure you want to delete Mata Kuliah "{{ item }}"?</p>

<div class="inaBox">
	<form action="{% url 'main:deletematkul' item.id %}"method="POST">
		{% csrf_token %}
		<button class="btn btn-first">
			<a href="{% url 'main:showmatkul' %}"> Cancel </a>
		</button>
		<button type="submit" class="btn btn-success" name="Confirm">Confirm</button>
		
	</form>
</div>

{% endblock %}

main/templates/main/story5-page1.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Mata Kuliah!{% endblock %}
{% load static %} 
{% block content%}
<form method="POST" style="padding-left: 40px; padding-top: 30px; padding-bottom: 30px">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="inaBox">
        <button class="btn btn-first" type="submit"> Submit</button>
    </div>
</form>
<div class="inaBox">
    <button class="btn btn-first">
        <a  href="{% url 'main:showmatkul' %}">Back</a>
    </button>
</div>

{% endblock %}

main/templates/main/story5-page2.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Mata Kuliah!{% endblock %}
{% block judulAtas %}Mata Kuliah{% endblock %}
{% load static %} 
{% block content%}
	<div class="inaBox">
	{% if matkuls %}
	<table border="0" width="60%" class="table table-borderless">
		<tr>
			<th>#</th>
			<th>Mata Kuliah</th>
			<th>Dosen</th>
			<th>Jumlah SKS</th>
			<th>Deskripsi</th>
			<th>Ruang Kelas</th>
			<th>DELETE</th>
		</tr>
	    {% for matkul in matkuls %}
	    <tr>
	    	<td>{{ forloop.counter }}</td>
	        <td>{{ matkul.nama_matkul }}</td>
	        <td>{{ matkul.dosen_pengajar }}</td>
	        <td>{{ matkul.jumlah_sks}}</td>
	        <td>{{ matkul.deskripsi }}</td>
	        <td>{{ matkul.ruang_kelas }}</td>
	        <td><a class="btn btn-danger" href="{% url 'main:deletematkul' matkul.id %}">Delete</a></td>
	    </tr>
	    {% endfor %}
	</table>
	{% else %}
	<h1> Rio belum mengambil mata kuliah apapun. </h1>
	{% endif %}
	</div>


    <div class="textcenter">
        <a class="btn btn-first" href="{% url 'main:home' %}"> Back</a>
        <a class="btn btn-second" href="{% url 'main:addmatkul' %}"> Add</a>
    </div>


{% endblock %}

story6/templates/story6/addKegiatan.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Tambah Kegiatan {% endblock %}
{% block judulAtas %} Kegiatankuuu {% endblock %}
{% block content %}
<form method="POST" style="padding-left: 40px; padding-top: 30px; padding-bottom: 30px">
    {% csrf_token %}
    {{ form }}
    <div class="inaBox">
        <button class="btn btn-first" type="submit"> Submit</button>
    </div>
</form>
{% endblock %}

story6/templates/story6/addPeserta.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Kegiatanku {% endblock %}
{% block judulAtas %} Tambah Peserta {% endblock %}
{% block content %}

<form method="POST" style="padding-left: 40px; padding-top: 30px; padding-bottom: 30px">
    {% csrf_token %}
    {{form}}
    <div class="inaBox">
        <button class="btn btn-first" type="submit"> Submit</button>
    </div>
</form>

{% endblock %}

story6/templates/story6/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}Rio Fernando Alexander{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-style">
            <h2 id=judul>{% block judulAtas %}Rio Fernando{% endblock %}</h2>
            
        </nav>
    </header>
    
   {% block content %}
   {% endblock %}
    

    
</body>
</html>

story6/templates/story6/kegiatan.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Kegiatanku {% endblock %}
{% block judulAtas %} Kegiatankuuuu {% endblock %}
{% block content %}

<div class="container text-center">

	
	<div class="row">
		
		{% for kegiatan in kegiatans %}
		<div class="col col-md-4">
			<div class="border border-dark" style="padding: 7%; margin: 10%;">

				<h3> {{kegiatan.name}} </h3>
				<ul>
					{% for orang in kegiatan.peserta.all %}
					<li><p>{{orang}}</p></li>
					{% endfor %}
				</ul>
				<div class="text-center">
					<a class="btn btn-first" href="{% url 'story6:addPeserta' kegiatan.id %}">Add peserta</a>
				</div>
			</div>
			
		</div>
		{% endfor %}

	</div>
	

</div>


<div class="text-center">
	<a class="btn btn-first" href="{% url 'story6:addKegiatan' %}"> Add Kegiatan</a>
</div>
{% endblock %}

story7/templates/story7/index.html
{% extends 'base.html' %}

{% block title %}Story 7{% endblock %}
{% block judulAtas %}Implementation of JavaScript and Jquery{% endblock %}

{% block content %}
	<style>
		p    {
			color: black;
			font-size: 13px;
		}
	</style>

	<div class="inaBox">
		<h1>
			ACCORDIONQ
		</h1>
	</div>
	<div class="inaBox">
		<div id="accordion">
		  	<h3 class="section" id=1>Activity
		  			<button class="arrow up" style="float: right; margin:6px;"> </button>
		  			<button class="arrow down" style="float: right; margin:6px;"></button>
		  	</h3>
		  	<div class="section-content" id=1>
			    <p>
			    	Currently, my main activity is studying at Universitas Indonesia. 
			    </p>
		  	</div>
		  	<h3 class="section" id=2>Hobbies
		  			<button class="arrow up" style="float: right; margin:6px;"> </button>
		  			<button class="arrow down" style="float: right; margin:6px;"></button>
		  	</h3>
		  	<div class="section-content" id=2>
			    <p>
			    I love to read
			    </p>
		  	</div>
		  	<h3 class="section" id=3>Organization
		  			<button class="arrow up" style="float: right; margin:6px;"> </button>
		  			<button class="arrow down" style="float: right; margin:6px;"></button>
		  	</h3>
		  	<div class="section-content" id=3>
			    <ul>
				    <li>Staff of Business IT Case at Compfest 2020</li>
			    </ul>
		  	</div>
		  	<h3 class="section" id=3>Courses
		  			<button class="arrow up" style="float: right; margin:6px;"> </button>
		  			<button class="arrow down" style="float: right; margin:6px;"></button>
		  	</h3>
	  		<div class="section-content" id=3>
	  			<ul>
				    <li>PPW</li>
			    </ul>
	  		</div>
		</div>
	</div>

{% endblock %}

story8/templates/story8/index.html
{% extends 'base.html' %}
{% block title %} Story8 {% endblock %}
{% block judulAtas %} Search for book {% endblock %}

{% block content %}
<div class="inaBox">
    <label class="col-sm-2 col-form-label">Search:</label>
    <input type="text" class="form-control" id="searchkey" placeholder="Masukkan kata kunci...">
</div>

<div class="inaBox">
	<table border="0" width="60%" class="table table-borderless" id="tabelbuku">
	</table>
</div>

<script type="text/javascript">
	$('#searchkey').keyup(function(){
  		var ketikan = $('#searchkey').val();
  		//console.log(ketikan);
  		$.ajax({
  			url: '/story8/data?q=' + ketikan,
  			success: function(data){
  				//console.log(data);
  				var objects = data.items;
          $('#tabelbuku').empty();
          $('#tabelbuku').append('<tr><th>#</th><th>Thumbnail</th><th colspan=4>Judul</th><th>link</th></tr>')
  				for (i = 1; i < objects.length + 1; i++) {
  					var judul = objects[i-1].volumeInfo.title;
  					var smallThumbnail = objects[i-1].volumeInfo.imageLinks.smallThumbnail;
  					var link = objects[i-1].volumeInfo.infoLink;
  					console.log(link);
  					$('#tabelbuku').append('<tr><td>' + i + '</td><td><img src="' + smallThumbnail + '"></img></td><td colspan=4>' + judul + '</td><td><a href="' + link + '">View</a></td></tr>' );
				  } 
  			}
  		});
	});
</script>



{% endblock %}

story9/templates/story9/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}Rio Fernando Alexander{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
</head>
<body>

<nav class="navbar navbar-default" style="background-color: darkorange; border-color: darkorange">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'story9:index' %}" style="color:white">{% block judulAtas %}Story9{% endblock %}</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'main:home' %}" style="background-color: darkorange; color:white">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% block login_nav %}
            {% endblock %}
        </ul>
    </div>
</nav>

   
{% block content %}
{% endblock %}
    

    
</body>
</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %}

{% block title %}Story 9{% endblock %}


{% block login_nav%}
{% if user.is_authenticated %}
	<li><a style="color:white"><span class="glyphicon glyphicon-user"></span> {{ user.email }}</a></li>
    <li><a href="/admin/logout/?next=/story9" style="color:white"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
{% else %}
	<li><a href="{% url 'story9:signup' %}" style="color:white"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
     <li><a href="/story9/login" style="color:white"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
{% endif %}
{% endblock %}



{% block content %}

<div class="text-center">
	{% if user.is_authenticated %}
    	<p>Welcome, {{ user.get_username }}. Thanks for logging in.</p>
	{% else %}
    	<p>Welcome, new user. Please log in.</p>
	{% endif %}
</div>

{% endblock %}

story9/templates/story9/login.html
{% extends 'story9/base.html' %}

{% block content %}

<div class="textcenter">
	<h1> Log in</h1>
</div>

<div class="inaBox">
	<form method="POST">
		{% csrf_token %}
		<label> Username </label>
		<input type="text" name="username" placeholder="Username..." class="form-control">
		<label> Password </label>
		<input type="password" name="password" placeholder="Password..." class="form-control" >
		<br>	
		{% if error_message %}
			<p>{{error_message}}</p>
		{% endif %}
		<br>
	    <button class="btn btn-first" type="submit"> Submit</button>
	    
	</form>

</div>
{% endblock %}

story9/templates/story9/signup.html
{% extends 'story9/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="textcenter">
	<h1> Sign Up</h1>
</div>

<div class="inaBox">
	<form method="POST" action="">

		{% csrf_token %}
		{{ form|crispy }}
		{{ form.errors }}
		<div class="inaBox">
	        <button class="btn btn-first" type="submit"> Submit</button>
	    </div>
	</form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}Rio Fernando Alexander{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

</head>
<body>
    <header class="header">
        <nav class="navbar navbar-style">
            <h2 id=judul>{% block judulAtas %}Rio Fernando{% endblock %}</h2>
            
        </nav>
    </header>
    
   {% block content %}
   {% endblock %}
    

    
</body>
</html>